### ISSUE TITLE
Dividers not showing in sidebar

### ISSUE THREAD

**Issue by sbormann** [niuiic/divider.vs#1]
Hi,
i created a divider like that:
````
"divider.divider": [
        {
        "level": 1,
        "dividerRegex": "//\\++ [\\S\\s]+ \\++",
        "textRegex": "//\\++ [\\S\\s]+ \\++",
        "color": "red",
        "list": true
        }
    ]
````

But it does not show in the list in the sidebar. Any suggestions?
Many thanks!

**Comment by niuiic** [comment]
` "textRegex": "//\\++ [\\S\\s]+ \\++"` -> `"textRegex": "//\\++ ([\\S\\s]+) \\++"`

`()` is missing

**Comment by sbormann** [comment]
Many thanks! It works!!
